// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddWorkspace'](arg1, arg2, arg3);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateToolProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateToolProfile'](arg1, arg2, arg3);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteToolProfile(arg1) {
  return window['go']['main']['App']['DeleteToolProfile'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetAdaConfig() {
  return window['go']['main']['App']['GetAdaConfig']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetProvidersConfig() {
  return window['go']['main']['App']['GetProvidersConfig']();
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetToolProfiles() {
  return window['go']['main']['App']['GetToolProfiles']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveModel(arg1, arg2) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SaveProvidersConfig() {
  return window['go']['main']['App']['SaveProvidersConfig']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetAdaConfig(arg1) {
  return window['go']['main']['App']['SetAdaConfig'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function ToggleProfileTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleProfileTool'](arg1, arg2, arg3);
}

export function ToggleTool(arg1, arg2) {
  return window['go']['main']['App']['ToggleTool'](arg1, arg2);
}

export function ToggleWorkspace(arg1) {
  return window['go']['main']['App']['ToggleWorkspace'](arg1);
}

export function UpdateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1, arg2);
}
