// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';
import {registry} from '../models';

export function AddToolToWorkspace(arg1:string,arg2:string):Promise<boolean>;

export function AddToolsToProfile(arg1:number,arg2:Array<string>):Promise<boolean>;

export function AddWorkspace(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AnswerApproval(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function AnswerQuestion(arg1:string,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<backend.ChatSession>;

export function CreateSummarizedSession(arg1:string,arg2:string,arg3:string):Promise<backend.ChatSession>;

export function CreateToolProfile(arg1:string,arg2:string,arg3:string):Promise<backend.ToolProfile>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteToolProfile(arg1:number):Promise<boolean>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function FetchProviderModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<backend.ProviderModel>>;

export function GetAdaConfig():Promise<backend.AdaConfig>;

export function GetAgentCategories():Promise<Array<string>>;

export function GetAgents():Promise<Array<backend.AgentConfig>>;

export function GetArchitectures():Promise<Array<main.architecture>>;

export function GetAvailableTools():Promise<Array<backend.ToolUIInfo>>;

export function GetExperts():Promise<Array<registry.ExpertPlugin>>;

export function GetInstalledSkills():Promise<Array<string>>;

export function GetPatterns(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPredefinedConnections():Promise<Array<backend.ConnectionDefinition>>;

export function GetProviders():Promise<Array<string>>;

export function GetProvidersConfig():Promise<Record<string, backend.ProviderConfig>>;

export function GetSessions(arg1:string):Promise<Array<backend.ChatSession>>;

export function GetSkillDetails(arg1:string):Promise<string>;

export function GetSkillFullInfo(arg1:string):Promise<backend.SkillFullInfo>;

export function GetToolProfile(arg1:number):Promise<backend.ToolProfile>;

export function GetToolProfiles():Promise<Array<backend.ToolProfile>>;

export function GetWorkerCategories():Promise<Array<string>>;

export function GetWorkers():Promise<Array<backend.WorkerConfig>>;

export function GetWorkspaces():Promise<Array<backend.WorkspaceConfig>>;

export function InstallSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListChatProviders():Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RemoveModel(arg1:string,arg2:string):Promise<void>;

export function RemoveToolFromWorkspace(arg1:string,arg2:string):Promise<boolean>;

export function RemoveToolsFromProfile(arg1:number,arg2:Array<string>):Promise<boolean>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveCustomSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveProvidersConfig():Promise<void>;

export function SearchSkills(arg1:string):Promise<Array<backend.SearchResult>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SetActiveWorkspace(arg1:string):Promise<void>;

export function SetAdaConfig(arg1:backend.AdaConfig):Promise<void>;

export function SetAgentCategories(arg1:Array<string>):Promise<void>;

export function SetAgents(arg1:Array<backend.AgentConfig>):Promise<void>;

export function SetWorkerCategories(arg1:Array<string>):Promise<void>;

export function SetWorkers(arg1:Array<backend.WorkerConfig>):Promise<void>;

export function SetWorkspaceTools(arg1:string,arg2:Array<string>):Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<backend.ConnectionTestResult>;

export function TestProviderConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.ProviderTestResult>;

export function TogglePin(arg1:string):Promise<void>;

export function ToggleProfileTool(arg1:number,arg2:string,arg3:boolean):Promise<boolean>;

export function ToggleTool(arg1:string,arg2:boolean):Promise<void>;

export function ToggleWorkspace(arg1:string):Promise<void>;

export function UninstallSkill(arg1:string):Promise<void>;

export function UpdateWorkspace(arg1:string,arg2:backend.WorkspaceConfig):Promise<void>;
